### ISSUE TITLE
Game1: Scaling problem

### ISSUE THREAD

**Issue by Magalii** [OpenWeek/app-for-a-KAP#20]
There are some scaling problems while playing this game:
I have tested the game with 3 different emulated phones and screen sizes.
- With a small screen (3,2") and 'notlong' ratio, the area of the game is reduced to only a small part of the screen (Tested with emulator 3.2 QVGA (ADP2) and with Android 7.0 and 9.0)
- Mireille can have different number of lanes depending of the screen size. She has 2 lanes on the smallest devices (3.2 QVGA, 3,2"), 3 lanes and an small inaccessible area on the extreme right on the large device (Galaxy Nexus, 4,65") and has 4 lanes on the largest one (Pixel 3 XL, 6,3"). However, the 'enemies' are always correctly divided in 3 lanes. It leads to having the same 'lane' of enemy being able to touch Mireille in two different possible lanes. Also, the size of Mireille and of the enemies is not proportionate on all devices, enemies tend to be too big.
- The text is not displayed on screen while the game is on with the biggest screen (Pixel 3 XL, 6,3"), but only appears after the game is finished. This could also be due to bad scaling.

**Comment by FrancoisDuchene** [comment]
The bug has been fixed. I discovered that it was actually already fixed by the commit fc49a8b701635ec5c0ab6ec6e05e3f7658bcd808, but a line has been accidentally modified by commit f060a2797d2ce76acf8efe8d9d0163d4908e0f60, causing the bug to come back.
I consider it to be fixed by now, but feel free to add in the conversation if you find more bugs.
